import { LegalPage } from "@/components/LegalPage";

const Terms = () => (
  <LegalPage title="Terms of Service" updated="April 29, 2026">
    <section>
      <h2>1. Agreement</h2>
      <p>
        These Terms govern your access to and use of Fix My UX (the "Service"). By creating an
        account or using the Service you agree to these Terms. If you are using the Service on
        behalf of an organization, you represent that you have authority to bind that organization.
      </p>
    </section>

    <section>
      <h2>2. The Service</h2>
      <p>
        Fix My UX provides AI-assisted heuristic UX audits of screenshots and URLs you submit.
        Outputs are generated by third-party AI models (currently Google Gemini) and are
        provided "as is" for guidance. They are not a substitute for professional usability
        testing or legal/accessibility compliance review.
      </p>
    </section>

    <section>
      <h2>3. Accounts</h2>
      <p>
        You must provide accurate information when registering and keep your credentials secure.
        You are responsible for all activity under your account. Notify us immediately of any
        unauthorized use.
      </p>
    </section>

    <section>
      <h2>4. Plans, credits and billing</h2>
      <ul>
        <li>Free accounts include a limited number of audits.</li>
        <li>Paid plans grant credits or unlimited usage as described on the Pricing page.</li>
        <li>
          Subscriptions renew automatically at the end of each billing period until cancelled.
          You can cancel at any time from your Account page; cancellation takes effect at the end
          of the current period.
        </li>
        <li>Payments are processed by Stripe and/or Paddle, who act as merchant of record where applicable.</li>
        <li>Prices may change with 30 days' notice for active subscribers.</li>
      </ul>
    </section>

    <section>
      <h2>5. Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Submit content you do not have the right to analyze, including confidential third-party material.</li>
        <li>Upload illegal, infringing, harmful, or sexually explicit content.</li>
        <li>Attempt to reverse-engineer, scrape, or overload the Service.</li>
        <li>Use the Service to build a competing AI audit product or to train competing models.</li>
        <li>Resell or sublicense access without our written consent.</li>
      </ul>
    </section>

    <section>
      <h2>6. Your content</h2>
      <p>
        You retain ownership of the screenshots, URLs, and descriptions you submit. You grant us
        a worldwide, non-exclusive, royalty-free license to host, process and analyze your
        submissions for the sole purpose of providing the Service to you. Generated reports are
        yours to use for any lawful purpose.
      </p>
    </section>

    <section>
      <h2>7. AI output disclaimer</h2>
      <p>
        AI-generated reports may contain inaccuracies or omissions. You are responsible for
        evaluating outputs before acting on them. We make no warranty that audits are correct,
        complete, or fit for any specific purpose.
      </p>
    </section>

    <section>
      <h2>8. Intellectual property</h2>
      <p>
        The Service, including its design, code, prompts, and branding, is owned by us and our
        licensors and is protected by intellectual property laws. We grant you a limited,
        revocable, non-transferable license to use the Service in accordance with these Terms.
      </p>
    </section>

    <section>
      <h2>9. Termination</h2>
      <p>
        You may stop using the Service at any time. We may suspend or terminate accounts that
        violate these Terms or that pose a risk to the Service or other users. Upon termination,
        your right to use the Service ends; data may be deleted in accordance with our Privacy
        Policy.
      </p>
    </section>

    <section>
      <h2>10. Disclaimers</h2>
      <p>
        THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND,
        EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND
        NON-INFRINGEMENT.
      </p>
    </section>

    <section>
      <h2>11. Limitation of liability</h2>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, OUR TOTAL LIABILITY FOR ANY CLAIM ARISING OUT OF
        OR RELATING TO THE SERVICE WILL NOT EXCEED THE AMOUNT YOU PAID US IN THE 12 MONTHS
        PRECEDING THE CLAIM. WE WILL NOT BE LIABLE FOR INDIRECT, INCIDENTAL, OR CONSEQUENTIAL
        DAMAGES.
      </p>
    </section>

    <section>
      <h2>12. Governing law</h2>
      <p>
        These Terms are governed by the laws of the jurisdiction in which our company is
        established, without regard to conflict-of-laws principles. Disputes will be resolved in
        the competent courts of that jurisdiction.
      </p>
    </section>

    <section>
      <h2>13. Changes</h2>
      <p>
        We may update these Terms occasionally. We will notify you of material changes. Your
        continued use after the effective date constitutes acceptance.
      </p>
    </section>

    <section>
      <h2>14. Contact</h2>
      <p>
        Questions: <a href="mailto:support@fixmyux.app">support@fixmyux.app</a>.
      </p>
    </section>
  </LegalPage>
);

export default Terms;
